# -*- coding: utf-8 -*-
"""
Created on Mon Jan  2 12:13:35 2023

@author: Matth
"""

#set game window
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600

# define game variable
ROUND_OVER_COOLDOWN = 3100

# Define general graphic and textures
RED = (255,0,0)
YELLOW = (255,255,0)
WHITE = (255,255,255)

# TILESIZE
#TILE_MAIN
#TILE_MEDIUM
#TILE_SMALL

# game variable
FPS=40

# define characteristics of PLAYERS
WARRIOR_HEALTH = 100
WARRIOR_SPEED = 10
WARRIOR_STRENGTH = 10
WIZARD_HEALTH = 100
WIZARD_SPEED =10
WIZARD_STRENGTH = 10
JS_HEALTH = 100
JS_SPEED =10
JS_STRENGTH = 10

# define fighter images characteristics - there are square on the image
WARRIOR_SIZE = 162
WARRIOR_SCALE = 3
WARRIOR_OFFSET = [65,40]
WIZARD_SIZE = 250
WIZARD_SCALE = 3
WIZARD_OFFSET = [112,106]
JS_SIZE = 470
JS_SCALE = 0.6
JS_OFFSET = [100,60]

# define number of steps in the animations
WARRIOR_ANIMATION_STEPS = [10,8,3,7,7,3,7,3,7]
WIZARD_ANIMATION_STEPS = [8,8,1,8,8,3,7]
JS1_ANIMATION_STEPS = [6,6,1,5,5,3,5,1,5]
JS2_ANIMATION_STEPS = [6,6,1,5,3,1,5,1,4]
JS3_ANIMATION_STEPS = [6,6,1,5,4,3,5,1,5]
JS4_ANIMATION_STEPS = [6,6,1,5,4,3,5,1,5]
JS5_ANIMATION_STEPS = [6,6,1,5,6,3,5,1,5]
JS6_ANIMATION_STEPS = [6,6,1,5,5,3,5,1,6]

WARRIOR_DATA = [WARRIOR_SIZE, WARRIOR_SCALE,WARRIOR_OFFSET]
WARRIOR_GAME_DATA = [WARRIOR_HEALTH,WARRIOR_SPEED,WARRIOR_STRENGTH]
WIZARD_DATA = [WIZARD_SIZE, WIZARD_SCALE,WIZARD_OFFSET]
WIZARD_GAME_DATA = [WIZARD_HEALTH,WIZARD_SPEED,WIZARD_STRENGTH]

JS_DATA = [JS_SIZE,JS_SCALE,JS_OFFSET]
JS_GAME_DATA = [JS_HEALTH,JS_SPEED,JS_STRENGTH]
JS2_DATA = [JS_SIZE,JS_SCALE,JS_OFFSET]
JS2_GAME_DATA = [JS_HEALTH,JS_SPEED,JS_STRENGTH]
JS3_DATA = [JS_SIZE,JS_SCALE,JS_OFFSET]
JS3_GAME_DATA = [JS_HEALTH,JS_SPEED,JS_STRENGTH]
JS4_DATA = [JS_SIZE,JS_SCALE,JS_OFFSET]
JS4_GAME_DATA = [JS_HEALTH,JS_SPEED,JS_STRENGTH]


